# Generated by Django 6.0.1 on 2026-02-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_film_category_film_created_at_film_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
